# Generated by Django 4.2.2 on 2023-06-07 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ["pk"],
                "verbose_name": "account",
                "verbose_name_plural": "accounts",
            },
        ),
        migrations.AlterModelTable(
            name="account",
            table="backend_account",
        ),
    ]
