# Generated by Django 4.2.2 on 2023-06-26 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="selected_bot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.bot",
                verbose_name="selected bot",
            ),
        ),
    ]
