# Generated by Django 4.2.2 on 2023-07-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("backend", "0005_account_selected_bot"),
    ]

    operations = [
        migrations.CreateModel(
            name="NLPBot",
            fields=[
                (
                    "bot_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="backend.bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "nlp bot",
                "verbose_name_plural": "nlp bots",
                "db_table": "nlp_bot",
                "ordering": ["pk"],
            },
            bases=("backend.bot",),
        ),
    ]
