# Generated by Django 4.2.2 on 2023-07-30 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nlp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_name", models.CharField(max_length=100)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlp.nlpbot",
                        verbose_name="nlp bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "entity",
                "verbose_name_plural": "entities",
                "db_table": "nlp_entity",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Intent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("intent_name", models.CharField(max_length=100)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlp.nlpbot",
                        verbose_name="nlp bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "intent",
                "verbose_name_plural": "intents",
                "db_table": "nlp_intent",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("response", models.TextField(verbose_name="response")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("INSTANT", "Instant response"),
                            ("COLLECT", "Collect response"),
                            ("PROVIDE", "Provide response"),
                        ],
                        default="INSTANT",
                        max_length=64,
                        verbose_name="default response type",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlp.intent",
                        verbose_name="intent",
                    ),
                ),
            ],
            options={
                "verbose_name": "response",
                "verbose_name_plural": "responses",
                "db_table": "nlp_response",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="TrainingPhrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phrase", models.TextField(verbose_name="phrase")),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlp.intent",
                        verbose_name="intent",
                    ),
                ),
            ],
            options={
                "verbose_name": "training phrase",
                "verbose_name_plural": "training phrases",
                "db_table": "nlp_training_phrase",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="ResponseEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlp.entity",
                        verbose_name="entity",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlp.response",
                        verbose_name="response",
                    ),
                ),
            ],
            options={
                "verbose_name": "response entity mapping",
                "verbose_name_plural": "response entity mapping",
                "db_table": "nlp_response_entity",
                "ordering": ["response"],
            },
        ),
        migrations.CreateModel(
            name="EntityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category_name", models.CharField(max_length=100)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlp.nlpbot",
                        verbose_name="nlp bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "entity category",
                "verbose_name_plural": "entity categories",
                "db_table": "nlp_entity_category",
                "ordering": ["pk"],
            },
        ),
    ]
