# Generated by Django 4.2.2 on 2023-08-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nlp", "0004_entity_synonym_alter_entity_entity_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="entity_name",
            field=models.CharField(max_length=100, verbose_name="entity name"),
        ),
        migrations.AlterField(
            model_name="entity",
            name="synonym",
            field=models.CharField(blank=True, null=True, verbose_name="synonym"),
        ),
    ]
