# Generated by Django 4.2.2 on 2023-08-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nlp", "0006_responseentitycategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intent",
            name="intent_name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="intent name"
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("INSTANT", "Instant response"),
                    ("COLLECT", "Collect response"),
                    ("PROVIDE", "Provide response"),
                ],
                default="INSTANT",
                max_length=64,
                verbose_name="response type",
            ),
        ),
    ]
