# Generated by Django 4.2.2 on 2023-08-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nlp", "0007_alter_intent_intent_name_alter_response_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intent",
            name="intent_name",
            field=models.CharField(max_length=100, verbose_name="intent name"),
        ),
    ]
