# Generated by Django 4.2.2 on 2023-08-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nlp", "0008_alter_intent_intent_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitycategory",
            name="synonym",
            field=models.CharField(blank=True, null=True, verbose_name="synonym"),
        ),
        migrations.AlterField(
            model_name="response",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("INSTANT", "Instant response"),
                    ("COLLECT", "Collect response"),
                    ("PROVIDE", "Provide response"),
                    ("PROVIDE_CONFIRM", "Provide Confirm response"),
                    ("CONFIRM_POSITIVE_COLLECT", "Provide Confirm Collect response"),
                    ("CONFIRM_POSITIVE", "Positive response"),
                    ("CONFIRM_NEGATIVE", "Negative response"),
                ],
                default="INSTANT",
                max_length=64,
                verbose_name="response type",
            ),
        ),
    ]
