# Generated by Django 4.2.2 on 2023-06-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_bot"),
        ("keywordrecognition", "0003_remove_elizabot_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elizabot",
            name="bot_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="backend.bot",
            ),
        ),
    ]
