# Generated by Django 4.2.2 on 2023-06-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keywordrecognition", "0004_alter_elizabot_bot_ptr"),
    ]

    operations = [
        migrations.AddField(
            model_name="decomp",
            name="weight",
            field=models.IntegerField(default=1, verbose_name="weight"),
        ),
    ]
