# Generated by Django 4.2.2 on 2023-06-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("keywordrecognition", "0006_synonym_bot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synonym",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="keywordrecognition.elizabot",
                verbose_name="bot",
            ),
        ),
    ]
