# Generated by Django 4.2.2 on 2023-06-28 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("keywordrecognition", "0007_alter_synonym_bot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="synonym",
            options={
                "ordering": ["value"],
                "verbose_name": "synonym",
                "verbose_name_plural": "synonyms",
            },
        ),
    ]
