name: Django CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.3.2
      - name: psycopg2 prerequisites
        run: sudo apt-get --assume-yes install libpq-dev python-setuptools
      - name: Install dependencies
        run: poetry install
      - name: Run flake8
        run: poetry run flake8
      - name: Run tests
        run: poetry run coverage run --source='.' manage.py test --noinput && poetry run coverage xml
        env:
          ENVIRONMENT: development
          DJANGO_LOG_LEVEL: DEBUG
          SECRET_KEY: 2dkvq6s&lin&tr
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_EXPOSE_PORT: 5432
          FIREBASE_WEB_API_KEY: ${{ secrets.DEV_FIREBASE_WEB_API_KEY}}
          FIREBASE_PROJECT_ID: ${{ secrets.DEV_FIREBASE_PROJECT_ID}}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.DEV_FIREBASE_PRIVATE_KEY_ID}}
          FIREBASE_PRIVATE_KEY: ${{ secrets.DEV_FIREBASE_PRIVATE_KEY}}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.DEV_FIREBASE_CLIENT_EMAIL}}
          FIREBASE_CLIENT_ID: ${{ secrets.DEV_FIREBASE_CLIENT_ID}}
          FIREBASE_CLIENT_CERT_URL: ${{ secrets.DEV_FIREBASE_CLIENT_CERT_URL}}
